### ISSUE TITLE
Add usage of Gradle Kotlin DSL plugin

### ISSUE THREAD

**Issue by vrudas** [Konstantion/java-formatter-plugin#1]
Currently, the implementation of `JavaFormatter` plugin is implemented with the usage of a Java DSL and Kotlin programming language. This reduces the amount of Kotlin features that can be used during development.

When the Gradle plugin https://plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl (de-facto standard plugin for development using Kotlin) is added we can get such results:
```kotlin
        extensions.getByType<SpotlessExtension>().java { ->
            lineEndings = LineEnding.PLATFORM_NATIVE
            prettier()
                .config(mapOf("parser" to "java"))
        }
```
instead of 
```kotlin
        extensions.getByType(SpotlessExtension::class.java).java { spotless ->
            spotless.lineEndings = LineEnding.PLATFORM_NATIVE
            spotless
                .prettier()
                .config(mapOf("parser" to "java"))
        }

```
and much more fluent DSL configs.

During the addition of the plugin please pay attention to Kotlin language version compatibility.

**Comment by Konstantion** [comment]
Thank you for the advice, I really appreciate it. I will apply these changes in the future.

**Comment by Konstantion** [comment]
Thank you for the advice, I really appreciate it. I will apply these changes in the future.
